sonar.projectKey=opensoft_ledgerlinc-model-ocr-pipeline
sonar.organization=opensoft
sonar.host.url=https://sonarcloud.io

sonar.sourceEncoding=UTF-8
sonar.python.version=3.12

sonar.sources=src
sonar.tests=tests/contract_tests,tests/pipeline_tests,tests/unit,tests/integration,tests/evaluator_tests

sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=tests/**,scripts/**,step2_ocr_ensemble.py
